### ISSUE TITLE
Nova says flake8 not found, which disagrees

### ISSUE THREAD

**Issue by barbequesauce** [flother/Blake.novaextension#3]
Really confused.... any ideas how to fix this?

<img width="1440" alt="Screen Shot 2021-06-17 at 8 22 31 PM" src="https://user-images.githubusercontent.com/25070944/122487727-eb5b8b80-cfa9-11eb-9586-379fe2d94960.png">

**Comment by flother** [comment]
Getting Python commands to run consistently from within GUIs is always a little tricky. By default, Blake will run Flake8 using `/usr/bin/env flake8` and so I'd imagine you have Flake installed somewhere that isn't available from your default shell environment. Two things come to mind:

1. You're using Zsh in the iTerm app. Is this your default shell? Is Flake8 only available in a special Zsh environment?
2. You have Flake8 installed in `/Users/patrick/.local/bin`. Is this directory included in your default shell's `PATH`?

I think that answering those questions will lead you to a solution.

If all else fails, you can configure the executable paths for Flake8 and Black on a per project basis within Nova (select _Project Settings..._ from the _Project menu_, and look for the Blake environment).

**Comment by mchccc** [comment]
Hello, I'm also having the same issue: I have all the executables needed installed in a virtual environment which is configured in Nova, is it possible for the extension to pick them up automatically from there? I really don't want them in my `PATH`, nor do I want to keep updating the extension's settings with obscure paths.

Thanks

**Comment by flother** [comment]
As far as I can tell, you can't know for sure where a Python project's virtual environment is in the file system. It's not like, say, npm, where you can look in a `node_modules/` sub-directory for a dependency. Python lets you put virtualenvs anywhere. For example, I keep my code in `~/repos` but my Python virtualenvs are in `~/.pyenv/versions`, and a repo and its virtualenv don't need to share a name. This means Blake can't really guess where to look, and so that's why you have to set it on a case-by-case basis in Nova.

However, one thing I did notice recently is that Nova allows you to have default settings for an extension, as well as settings for individual projects. I don't know if that's something that was added after I first wrote Blake, or whether I missed it back then, but either way it's something I could add to Blake. I could add default settings so that you could tell Blake to use a system-wide version of Black and Flake8 — ones installed by Homebrew, for example. You could still override it for a particular project, if you wanted to, using the project-specific settings.

What do you think? Does that sound useful?

**Comment by flother** [comment]
With [v0.7.0](https://github.com/flother/Blake.novaextension/releases/tag/v0.7.0) Blake will now:

1. Look for a project-specific preference for the location of Black and Flake8
2. Fall back to a global Nova-wide preference for the location of Black and Flake8
3. Otherwise fall back to `/usr/bin/env black` and `/usr/bin/env flake8`

I think this provides as much flexibility as possible given the limitations of Pythons virtual environments, so I'm going to close this issue. But please do comment or re-open if you think we could do better.
